// <auto-generated />
namespace ChildCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class identitymodelphotostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identitymodelphotostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201610122151323_identity model photo string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
