// <auto-generated />
namespace ChildCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class billingmodelcreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(billingmodelcreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201610171347126_billing model created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
