// <auto-generated />
namespace ChildCare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class medicationnotesaddedtochildtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(medicationnotesaddedtochildtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201610112217344_medication,notes added to child table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
